### ISSUE TITLE
Setting a new FDR threshold

### ISSUE THREAD

**Issue by FDallaPozza** [bartongroup/differr_nanopore_DRS#2]
Hi! I'm performing an analysis on a toy dataset, at the beginning I run the algorithm with the default --fdr-threshold value, then I try to relax the FDR to 1 because I wanted to obtain as output all the sites analysed by the tool. What I saw is that the result is the same as before with the default value. Isn't it possible to do that?

Fabio

**Comment by mparker2** [comment]
Hi Fabio,

Are you getting no results at all, or just the same set of results with both fdr settings?

Can you try setting fdr-threshold to 2? It might be that the remainder of the sites have FDR of 1.0 and they still get filtered at a threshold of 1 because the code uses less-than, not less-than-or-equal to filter. Probably it should use less-than-or-equal.

BW
Matt

**Comment by FDallaPozza** [comment]
I'm getting the same results (number of sites and values) using both fdr settings. As you adviced I tried also to set fdr-threshold to 2 but still the result it is the same.

**Comment by mparker2** [comment]
hmm OK. does your dataset have replicates? It also uses a G-test for homogeneity to filter positions where the total test statistic within replicates of the same condition is greater than the test statistic for differences between conditions.

If you want to prevent this behaviour you could comment out lines 118 and 119 in main.py:
https://github.com/bartongroup/differr_nanopore_DRS/blob/a554d00c894d76cd4e91e2312cf88d611b0af3d2/differr/main.py#L118-L119

The main reason for this is to help reduce false positives caused by other sources of basecall  profile variation i.e. technical variation. Removing this behaviour might increase the false positive rate.

BW
Matt

**Comment by FDallaPozza** [comment]
Ok understood, thank you for the help!

Fabio
